insert into user values(1, sysdate(), 'AB')
insert into user values(2, sysdate(), 'Jill')
insert into user values(3, sysdate(), 'Jam')
insert into post values(11001, 'I am the Body', 'I am the title', 2)
insert into post values(11002, 'I am the Body', 'I am the title', 2)